# Generated by Django 5.2.17 on 2026-09-14 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cash", models.BigIntegerField(default=10000000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [models.CheckConstraint(condition=models.Q(("cash__gte", 0)), name="nonnegative_cash")],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.UUIDField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=8)),
                ("side", models.CharField(max_length=4)),
                ("kind", models.CharField(max_length=6)),
                ("requested", models.PositiveIntegerField()),
                ("executed", models.PositiveIntegerField()),
                ("total", models.BigIntegerField()),
                ("status", models.CharField(max_length=12)),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="trading.account")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cash_delta", models.BigIntegerField()),
                ("cash_after", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trading.account")),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="trading.order")),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=8)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("cost", models.BigIntegerField(default=0)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="positions", to="trading.account")),
            ],
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(fields=("account", "key"), name="idempotent_order"),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(fields=("account", "symbol"), name="one_position_per_symbol"),
        ),
    ]
