# Generated by Django 5.2.17 on 2026-10-06 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def cash_anchors(apps, schema_editor):
    Account = apps.get_model("trading", "Account")
    Ledger = apps.get_model("trading", "LedgerEntry")
    for account in Account.objects.using(schema_editor.connection.alias).iterator():
        delta = Ledger.objects.using(schema_editor.connection.alias).filter(account_id=account.id).aggregate(value=models.Sum("cash_delta"))["value"] or 0
        Account.objects.using(schema_editor.connection.alias).filter(id=account.id).update(cash_anchor=account.cash - delta, history_epoch=uuid.uuid4())



class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auththrottle_account_user_account_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_anchor',
            field=models.BigIntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='account',
            name='history_epoch',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='order',
            name='limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='realized',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='reflection',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(default='ioc', max_length=8),
        ),
        migrations.CreateModel(
            name='OrderMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_delta', models.BigIntegerField()),
                ('cash_after', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.account')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='trading.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.CharField(max_length=40)),
                ('scenario_version', models.PositiveIntegerField(default=1)),
                ('start_key', models.UUIDField()),
                ('start_fingerprint', models.CharField(max_length=64)),
                ('state', models.JSONField(default=dict)),
                ('shared_token', models.UUIDField(null=True, unique=True)),
                ('share_notes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='trading.account')),
            ],
        ),
        migrations.CreateModel(
            name='ReplayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trading.replaysession')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.UUIDField()),
                ('bucket', models.DateTimeField()),
                ('cash', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('positions', models.JSONField(default=list)),
                ('prices', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trading.account')),
            ],
            options={
                'ordering': ['bucket'],
                'constraints': [models.UniqueConstraint(fields=('account', 'epoch', 'bucket'), name='one_valuation_per_minute')],
            },
        ),
        migrations.AddConstraint(
            model_name='replaysession',
            constraint=models.UniqueConstraint(fields=('account', 'start_key'), name='idempotent_replay_start'),
        ),
        migrations.AddConstraint(
            model_name='replayevent',
            constraint=models.UniqueConstraint(fields=('session', 'key'), name='idempotent_replay_action'),
        ),
        migrations.RunPython(cash_anchors, migrations.RunPython.noop),
    ]
