# Generated by Django 5.2.17 on 2026-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_account_cash_anchor_account_history_epoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
